### ISSUE TITLE
[FIX] funnyboard jar 파일 실행 관련 이슈

### ISSUE THREAD

**Issue by jinbokk** [J-SPOT/playground#11]
# 문제 발생 상황
- 카카오톡으로 안내받은 `java -jar funnyboard...` 명령어 입력시 `Error: Unable to access jarfile funnyboard...` 에러 발생.

# 임시 해결 방법
- build/libs 폴더에 `java -jar funnyboard-0.0.1-SNAPSHOT.jar` 파일과 `java -jar funnyboard-0.0.1-SNAPSHOT-plain.jar` 파일이 있는 것을 보고, 명령어를 `java -jar funnyboard-0.0.1-SNAPSHOT.jar` 라고 입력하니까 정상적으로 스프링 작동 되는 것을 확인하였음

# 이슈사항
- `java -jar` 명령어로 정확히 어떤 파일을 실행해야 하는지 여부
- 카카오톡으로 안내해준

> 3. terminal , backend폴더에 gradlew.bat 있는 폴더로 가기
> 4. ./gradlewbat clean build 
> 5. cd build/libs
> 6. java -jar funnyboard...

위 과정을 자동화하는 스크립트를 짤 수도 있을까요?

**Comment by ji-jjang** [comment]
6번에서 파일명 전부 입력하는 거 대신 ...이라고 표현한 거라 
java -jar funnyboard-0.0.1-SNAPSHOT.jar 이렇게 실행하시면 됩니다!
사진 자세히 보시면 이렇게 실행한 명령어가 보일겁니다 :)

**Comment by ji-jjang** [comment]
스프링 정상작동 확인하는 거 보셨으면 이슈 닫아도 된다고 봅니다,,!
